---
title: "Homework 4"
author: "Andrew Maloney"
date: "3/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Data 

```{r}
library(dplyr)
library(forcats)
library(ggplot2)
library(ggmosaic)

ChickWeight <- ChickWeight
glimpse(ChickWeight)
summary(ChickWeight)

```


```{r}

weight0 <- ChickWeight %>% group_by(Diet) %>% summarize(nChicks = n(), avgWeight = mean(weight, na.rm = TRUE), sd_weight = sd(weight, na.rm = TRUE))
print(weight0)

```


```{r}

tabulate(ChickWeight$Chick) # There are 5 chicks with counts < 12. Remove 

ChickWeight %>% group_by(Chick) %>% summarize(n = n())#Chicks 18, 16, 15, 8, and 44 all have less than 12 measurements

complete <- ChickWeight %>% group_by(Chick) %>% mutate(n = n()) %>% filter(n() == 12)
print(head(complete, 3))

```


```{r}

complete <- complete %>% group_by(Chick) %>% mutate(weightgain = weight[Time == Time] - weight[Time == 0])
complete
print(head(complete, 3))
```

```{r}
complete_21 <- complete %>% mutate(weightgain = weight[Time ==21])

complete_21 %>% ggplot(aes(x = reorder(Diet, weightgain, FUN = median), y = weightgain))+
  geom_boxplot(aes(fill = Diet)) + expand_limits(y = 0)+
   ggtitle("Weight Gain by Diet [Day 21]") + xlab("Diet") + ylab("Weight Gain") 

```



```{r}
complete %>% mutate(weightgain = sum(weightgain)) %>% distinct(weightgain) %>% arrange(weightgain)


complete %>% ggplot(aes(x = reorder(Chick, weightgain), y = weightgain, fill = Chick))+
  geom_boxplot() + coord_flip()+
  ggtitle("Comparing Recorded Chick's Weight Gain") + xlab("Chick") + ylab("Weight Gain") + theme(axis.text=element_text(size=7))

```

  

```{r}

Series <- complete %>% group_by(Chick) %>% mutate(weight_log = weight[Time == 0]) %>% filter(weight_log == 39 | weight_log == 43) %>% arrange(weight_log) 
print(Series)

Series %>% ggplot(aes(x = Time, y = weight, color = weight_log))+
  geom_line() + geom_point() + facet_wrap(~Chick, nrow = 2)+
  ggtitle("Growth Trajectories Over Time") + xlab("Time Recorded") + ylab("Weight Gained")

```






